import "./globals.css";
import Nav from "./auth/nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-20">
        <Nav />
        {children}
      </body>
    </html>
  );
}
